# Generated by Django 5.2.4 on 2025-11-20 06:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=255, null=True)),
                ('product_type', models.CharField(blank=True, max_length=100, null=True)),
                ('product_image_url', models.CharField(blank=True, max_length=255, null=True)),
                ('product_description', models.TextField(blank=True, null=True)),
                ('target_pet_type', models.CharField(blank=True, max_length=100, null=True)),
                ('min_follower_count', models.IntegerField(blank=True, null=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('application_deadline_at', models.DateTimeField(blank=True, null=True)),
                ('posting_start_at', models.DateTimeField(blank=True, null=True)),
                ('posting_end_at', models.DateTimeField(blank=True, null=True)),
                ('required_creator_count', models.IntegerField(blank=True, null=True)),
                ('campaign_status', models.CharField(default='DRAFT', max_length=20)),
                ('brand', models.ForeignKey(limit_choices_to={'account_type': 'brand'}, on_delete=django.db.models.deletion.CASCADE, related_name='campaigns_as_brand', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CampaignAcceptance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acceptance_status', models.CharField(blank=True, max_length=100, null=True)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('selected_at', models.DateTimeField(blank=True, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.campaign')),
                ('creator', models.ForeignKey(limit_choices_to={'account_type': 'creator'}, on_delete=django.db.models.deletion.CASCADE, related_name='applications_as_creator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Deliverable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('post_url', models.CharField(blank=True, max_length=255, null=True)),
                ('deliverable_status', models.CharField(blank=True, max_length=100, null=True)),
                ('brand_approval_at', models.DateTimeField(blank=True, null=True)),
                ('settlement_status', models.CharField(default='PENDING', max_length=20)),
                ('acceptance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliverables', to='myapp.campaignacceptance')),
            ],
        ),
    ]
